POST https://farmerecommerce.onrender.com/api/v1/admin
content-type: application/json

{
    "fullName": "Abel Kinfu",
    "image": "https://example.com/avatar.jpg",
    "userName": "abelk3",
    "password":"123456",
    "email": "abelk3@gmail.com",
    "phoneNumber": "936722189",
    "role": "Admin"
}
### 

POST https://farmerecommerce.onrender.com/api/v1/admin/login
content-type: application/json

{
    "password":"123456",
    "phoneNumber": "936722189"
}
###
POST https://farmerecommerce.onrender.com/api/v1/blog/
content-type: application/json

{
     "title": "Top 5 ",
    "image": "https://www.iwmi.cgiar.org/wp-content/uploads/2015/09/sudan_farmer.jpg",
    "content":"Hello"
}

###
GET https://farmerecommerce.onrender.com/api/v1/product

###
POST https://farmerecommerce.onrender.com/api/v1/product-category
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmYyZWI0NDBmYjdkYzlmYzQ2M2E2YSIsImlhdCI6MTcxMTg3MDM2NywiZXhwIjoxNzEyNzM0MzY3fQ.XQvxIO_PR12oMlXE-EX3PzMsOpNwPUO_9xYpr1_NjuM

{
    "name": "sample",
    "description":"kkkkk"
}

### 
Get https://farmerecommerce.onrender.com/api/v1/order

### 
GET https://farmerecommerce.onrender.com/api/v1/farmer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmYyZWI0NDBmYjdkYzlmYzQ2M2E2YSIsImlhdCI6MTcxMTg3MDM2NywiZXhwIjoxNzEyNzM0MzY3fQ.XQvxIO_PR12oMlXE-EX3PzMsOpNwPUO_9xYpr1_NjuM
